/* Note di versione, dalla più recente. Mostrate nel menu (voce "Novità") per i tester. */
export const CHANGELOG = [
  {
    v: 'v0.83', it: [
      'FIX stallo: consegnare/spedire i grezzi ora si AGGIUNGE al lotto già in lavorazione (prima con la borsa piena e un lotto non ritirato restavi bloccato); il Museo offre sempre "Consegna"',
      'CASSETTA DELLA POSTA nei borghi e nei paesi: spedisci i reperti grezzi al Museo senza il viaggio (🪙 2 a pezzo), sono pronti il giorno dopo e li ritiri al Museo',
      'Nuova meraviglia delle Dune: lo SCHELETRO DI DRAGO — uno dei figli di Neladan, disegnato a mano nello Sprite Studio (al posto del vecchio "Costolame"); non trema più mentre cammini',
      'MENHIR dei Prati ridisegnato a mano: un cerchio di pietre erette più bello e leggibile',
      'La MUSICA cambia bioma con ARMONIA: la tonalità passa a una vicina e sul tempo giusto, niente più stacchi stonati',
      'Il ritmo scivola da un bioma all\'altro invece di scattare di colpo',
      'Ogni nota ha un attacco più morbido: via i piccoli "click" fra un suono e l\'altro',
      'Gli oggetti di superficie uguali (conchiglie, funghi…) si IMPILANO: 1 riga con la quantità, non una lista infinita',
      'Il pannello del Maestro Scavatore va dritto al punto: livello, quanto manca e cosa dà il prossimo — via il muro di testo',
      'I tetti degli edifici mostrano il MATERIALE del bioma (coppi, conci, scandole, tegole, paglia, ardesia) e nelle Lande si innevano tutti',
      'RESTAURO in 3 passi al Museo: PENNELLO spolveri e il fossile compare · SCALPELLO lo stacchi dalla roccia · SPATOLA lo rifinisci — negli ultimi due serve precisione o si scheggia (Pulizia + Integrità)',
      'FONTANA: tre tiri di fila, ognuno più veloce — sbagliane uno e i tiri finiscono; tre su tre = premio assicurato, altrimenti in base a quanti ne azzecchi',
      'LUCCIOLE: missione RARA d\'estate dal cartello — di notte, all\'aperto, raccogli le lucciole col retino; completarla ti GUIDA a una mappa verso un fossile LEGGENDARIO',
      'LUCCIOLE: il contatore sta più in alto, fuori dal raggio del retino, così non copre più le lucciole che stai per prendere',
      'SUONO: il "trovato!" ora parte per OGNI reperto — anche con accetta e piccone (prima davano solo il colpo) e dai siti di scavo (che non lo facevano)',
      'LIBRO: ogni scheda mostra "Ossa: X/5" (i pezzi consegnati al Museo) e quando le hai TUTTE la pagina si borda d\'ORO con "✓ Completo"',
      'COMPAGNI: il potere ora dipende dai TRATTI — il TIPO (fonte: terra/acqua/albero/roccia/grotta) decide che aiuto dà, la RARITÀ quanto è forte; e ogni compagno dà comunque fiuto e bussola',
      'COMPAGNO di GROTTA = Lanterna: oltre ai cristalli più ricchi, di NOTTE all\'aperto allarga l\'alone di luce (scala con la rarità) — così serve anche in superficie, non solo in grotta',
      'CHIMERE: hanno SEMPRE DUE poteri (dal cranio e dalla zampa), ognuno più debole di un risveglio singolo ma sono due — estremità di tipo diverso = es. Pescatore +5% E Boscaiolo +5%; stesso tipo = quel tipo + un bonus UNIVERSALE (✨ Tuttofare: resa su tutte le raccolte). Nessuna chimera batte un risveglio sulla sua attività',
      'COMPAGNI LEGGENDARI: quelli di terra/acqua/roccia/albero RACCOLGONO da soli — vanno alla casella, lavorano con animazione e ti portano il fossile (lento e a zaino non pieno: lo scavo resta la fonte principale)',
      'FOSSILE VOLANTE: il compagno di GROTTA leggendario si CAVALCA (dallo zaino, sezione Mezzi) e sorvoli la mappa attraversando tutto — ma in grotta si scende e si cammina',
      'HACK (console) riordinati e raggruppati; nuovi per i compagni: companion=<tipo> (per provare i poteri), mount (cavalcatura volante), chimera',
      'CAVALCATURA rifinita: niente più compagno sdoppiato, faccia dell\'eroe libera e gambe in sella; in volo NON si scava (serve solo a muoversi veloce)',
      'COMPAGNI che GIRANO: muovendoti in su/giù il compagno (e la cavalcatura) mostra le viste di SPALLE e di FRONTE, non più solo di profilo',
      'CAVALCATURA: col compagno di grotta leggendario premi F per volare/scendere (o dallo zaino); l\'eroe è IN SELLA (non galleggia) e le ali si vedono da ogni lato',
      'CAVALCATURA rifatta: è lo STESSO Abissodonte che vedi nel libro/parco, con delle ALI membranose che gli spuntano dalla schiena, le ZAMPE raccolte in volo e l\'omino ben seduto in groppa (non più un drago a sé che stonava)',
      'FIX hack: "companion=grotta leggendario" (e "mount") ora ti dà l\'Abissodonte GIUSTO — prima spawnava per errore la specie di grotta comune',
      'FIX POSIZIONE/COMPAGNO al refresh: lo snapshot dei comandi ora è PER-SESSIONE (si azzera al caricamento). Prima persisteva e `vanilla` poteva ripristinare uno stato VECCHIO (vecchio compagno + vecchia posizione alla porta) sovrascrivendo la partita. Ora la partita coi comandi è semplicemente salvata; `vanilla` annulla solo i comandi di QUESTA sessione',
      'FIX: non ti riposiziona più alla porta quando ricarichi stando in un BOSCO (o in un punto chiuso ma valido): il soccorso scatta solo se la posizione è davvero murata',
      'FIX: il raccoglitore non "impazzisce" più partendo verso una casella in diagonale — il verso ora ha l\'isteresi (non flippa più profilo↔fronte a ogni frame)',
      'FIX: cambiando compagno il lavoro del vecchio si AZZERA subito — un compagno normale non continua più a "scavare" ereditando il job di un raccoglitore leggendario scelto prima (comando `compinfo` per vedere lo stato reale)',
      'FIX: il COMPAGNO raccoglitore leggendario non resta più "piantato" a scavare mentre ti allontani — se ti allontani molla il lavoro e ti raggiunge, poi riprende a raccogliere quando gli sei vicino',
      'FIX GROSSO: i COMANDI console non congelano più il salvataggio — giochi coi comandi e TUTTO si salva come una partita normale (prima al refresh tornavi indietro col vecchio compagno/posizione). Il primo comando fa uno snapshot pre-cheat che sopravvive al refresh; `vanilla` lo ripristina per annullare i cheat',
      'FIX: l\'icona del COMPAGNO nell\'HUD non è più nera/invisibile; e il compagno viene COPERTO dalle case quando ci passa dietro (prima ci si disegnava sopra)',
      'FIX TETTI: le tegole/scandole non "nuotano" più mentre cammini — il disegno del tetto era agganciato alla posizione sullo schermo invece che all\'edificio',
      'CAVALCATURA di profilo: l\'eroe è seduto più in basso, si vede una sola gamba sul fianco e l\'ala è adattata alla vista laterale',
      'FIX COMPAGNO SDOPPIATO: il compagno che è con te NON compare più anche nel recinto del parco; rimandandolo a casa ci rientra',
      'RACCOGLITORI: gli animali NON usano attrezzi — il pescatore ora fa come le oche (testa sotto, sedere fuori, zampe che remano), gli altri scavano/spingono e schizzano detrito (via canna/pala/accetta/piccone)',
      'CAVALCATURA: l\'eroe ora è SEDUTO in groppa (vita in su, gambe nascoste), non più in piedi; faccia libera e centrata',
      'SCAVO del compagno più bello: la creatura di TERRA scava a testa in giù come un cane — sedere e coda su che scodinzolano, zampe che grattano, terra che schizza indietro e mucchietto che cresce (niente più semplice affondo)',
      'TAGLIO ALBERO del compagno: la creatura ROSICCHIA il tronco come un castoro — morsi ritmici, trucioli di legno, tacca chiara e foglie che cadono ondeggiando dalla chioma (niente accetta)',
      'ROTTURA ROCCIA del compagno: la creatura TESTA il masso come un ariete — lampo d\'impatto, scaglie di pietra con scintille e una crepa che si apre (niente piccone)',
      'FIX: il compagno non TREMA più mentre cammini — l\'inseguimento aveva una zona morta che lo faceva partire e fermare di continuo; ora segue morbido',
      'FIX: in DIAGONALE il compagno non gira più all\'infinito fra profilo e fronte — ora tiene il verso finché un asse non domina davvero (isteresi)',
      'IMPOSTAZIONI: Lingua e Audio in cima, le Statistiche anonime in fondo a tutto',
    ], en: [
      'FIX deadlock: handing in / shipping raw finds now ADDS to the batch already in progress (before, with a full bag and an uncollected batch you got stuck); the Museum always offers "Hand in"',
      'MAILBOX in small and medium towns: ship your raw finds to the Museum without the trip (🪙 2 each); they\'re ready the next day and you collect them at the Museum',
      'New Dune wonder: the DRAGON SKELETON — one of Neladan\'s children, hand-drawn in the Sprite Studio (replacing the old "Great Ribcage"); no longer jitters as you walk',
      'MEADOW MENHIR redrawn by hand: a nicer, clearer circle of standing stones',
      'MUSIC changes biome in HARMONY: the key shifts to a near one, on the beat — no more jarring out-of-tune cuts',
      'The tempo slides from one biome to the next instead of snapping',
      'Every note has a softer attack: gone are the little clicks between sounds',
      'Identical surface objects (shells, mushrooms…) now STACK: one line with the count, not an endless list',
      'The Master Digger panel gets to the point: level, XP to go, next-level perks — no more wall of text',
      'Building roofs now show their biome MATERIAL (curved tiles, stone, shingles, tiles, thatch, slate) and get snow-capped in the Frozen Wastes',
      'RESTORATION in 3 steps at the Museum: BRUSH to reveal the fossil · CHISEL it free from the rock · SPATULA to finish — the last two need precision or you chip it (Cleaned + Intact)',
      'FOUNTAIN: three tosses in a row, each faster — miss one and the tosses end; three in a row = guaranteed prize, otherwise it depends on how many you land',
      'FIREFLIES: a RARE summer quest from the board — at night, outdoors, catch fireflies with a net; completing it GUIDES you to a map toward a LEGENDARY fossil',
      'FIREFLIES: the counter sits higher, outside the net\'s reach, so it no longer covers the fireflies you\'re about to catch',
      'SOUND: the "found!" chime now plays for EVERY fossil — with the axe and pickaxe too (they only made the tool hit) and from dig sites (which made none)',
      'BOOK: each page shows "Bones: X/5" (pieces handed to the Museum) and when you have them ALL the page gets a GOLD border with "✓ Complete"',
      'COMPANIONS: the power now depends on TRAITS — the TYPE (source: ground/water/tree/rock/cave) decides what help it gives, RARITY how strong; and every companion still grants sniff and compass',
      'CAVE companion = Lantern: besides richer crystals, at NIGHT outdoors it widens your light halo (scales with rarity) — so it helps on the surface too, not only in caves',
      'CHIMERAS: ALWAYS have TWO powers (from the skull and the leg), each weaker than a single awakened but there are two — different-type ends = e.g. Angler +5% AND Woodsman +5%; same type = that type + a UNIVERSAL bonus (✨ Versatile: yield on every kind of gathering). No chimera ever beats an awakened at its activity',
      'LEGENDARY COMPANIONS: the ground/water/rock/tree ones GATHER on their own — they walk to a tile, work with an animation and bring you the fossil (slow, and only when your bag isn\'t full: digging stays the main source)',
      'FLYING FOSSIL: the legendary CAVE companion can be RIDDEN (from the bag, Vehicles section) to fly over the map crossing anything — but in caves you land and walk',
      'Console HACKS tidied up and grouped; new companion ones: companion=<type> (to test powers), mount (flying ride), chimera',
      'FLYING RIDE polished: no more doubled companion, the hero\'s face stays clear and legs sit in the saddle; you CAN\'T dig while flying (it\'s just for fast travel)',
      'COMPANIONS that TURN: moving up/down the companion (and the mount) now shows BACK and FRONT views, not just the side',
      'MOUNT: with the legendary cave companion press F to fly/land (or from the bag); the hero SITS in the saddle (no longer floats) and the wings show from every side',
      'MOUNT redone: it\'s the SAME Abyssodont you see in the book/park, now with membrane WINGS sprouting from its back, LEGS tucked in flight and the hero sitting properly in the saddle (no more separate dragon that clashed)',
      'HACK FIX: "companion=grotta leggendario" (and "mount") now gives you the RIGHT Abyssodont — before it wrongly spawned the common cave species',
      'POSITION/COMPANION FIX on refresh: the command snapshot is now PER-SESSION (cleared on load). Before it persisted and `vanilla` could restore an OLD state (old companion + old door position), overwriting your game. Now a game played with commands is simply saved; `vanilla` only undoes THIS session\'s commands',
      'FIX: you\'re no longer teleported to a door when reloading while standing in a FOREST (or any enclosed but valid spot): the rescue only triggers if the position is truly walled in',
      'FIX: the gatherer no longer "goes crazy" when heading to a tile diagonally — its facing now has hysteresis (no more flipping side↔front every frame)',
      'FIX: switching companion now RESETS the previous one\'s work immediately — a normal companion no longer keeps "digging" by inheriting the job of a legendary gatherer picked earlier (`compinfo` command shows the real state)',
      'FIX: the legendary gatherer COMPANION no longer stays "planted" digging while you walk off — if you move away it drops the job and catches up, then resumes gathering when it is near you again',
      'BIG FIX: console COMMANDS no longer freeze the save — you play with commands and EVERYTHING saves like a normal game (before, a refresh threw you back with the old companion/position). The first command takes a pre-cheat snapshot that survives a refresh; `vanilla` restores it to undo the cheats',
      'FIX: the COMPANION icon in the HUD is no longer black/invisible; and buildings now occlude the companion when it passes behind them (before it drew on top)',
      'ROOF FIX: tiles/shingles no longer "swim" as you walk — the roof pattern was pinned to the screen position instead of the building',
      'MOUNT profile: the hero sits lower, only one leg shows on the near side, and the wing is adapted to the side view',
      'FIX DOUBLED COMPANION: the companion that\'s with you no longer also appears in the park pen; send it home and it returns there',
      'GATHERERS: animals DON\'T use tools — the angler now dabbles like a goose (head under, rump up, paddling feet), the others dig/shove and kick up debris (no rod/shovel/axe/pickaxe)',
      'MOUNT: the hero now SITS in the saddle (waist up, legs hidden), no longer standing; face clear and centered',
      'Nicer companion DIG: the ground gatherer digs head-down like a dog — rump and tail up wagging, paws scratching, dirt kicked backward and a growing mound (no more plain lunge)',
      'Companion TREE-CUTTING: the creature GNAWS the trunk like a beaver — rhythmic bites, wood chips, a pale notch and leaves fluttering down from the canopy (no axe)',
      'Companion ROCK-BREAKING: the creature HEADBUTTS the boulder like a ram — impact flash, stone chips with sparks and a crack opening up (no pickaxe)',
      'FIX: the companion no longer JITTERS as you walk — its follow had a dead zone that made it stop-and-go; now it trails smoothly',
      'FIX: moving DIAGONALLY the companion no longer flips endlessly between side and front — it keeps its facing until one axis clearly wins (hysteresis)',
      'SETTINGS: Language and Audio on top, Anonymous stats at the very bottom',
    ],
  },
  {
    v: 'v0.80', it: [
      'DIGSY SI INSTALLA: icona sulla schermata, a tutto schermo, e funziona ANCHE SENZA RETE',
      'Il pulsante "Installa Digsy" nel menu (su iPhone spiega i passi, che lì nessuno indovina)',
      'Il salvataggio è protetto dalle pulizie automatiche del telefono',
    ], en: [
      'DIGSY INSTALLS: icon on your home screen, full-screen, and it works EVEN OFFLINE',
      'An "Install Digsy" button in the menu (on iPhone it explains the steps, which nobody guesses)',
      'Your save is protected from the phone\'s automatic clean-ups',
    ],
  },
  {
    v: 'v0.75', it: [
      'Il motto è ESPLORA · SCAVA · SCOPRI, che è anche l\'ordine in cui si gioca',
      'Un verbo solo per la stessa cosa: si RISVEGLIA (non si rianima) sia una specie sia una chimera',
      'Colori e spaziature del gioco raccolti in un posto solo: le schermate nuove partono già in tinta',
    ], en: [
      'The tagline is EXPLORE · DIG · DISCOVER, which is also the order you play in',
      'One verb for one thing: you AWAKEN a species and a chimera alike',
      'Colours and spacing gathered in one place: new screens start out in tune',
    ],
  },
  {
    v: 'v0.74', it: [
      'IMPOSTAZIONI: tutti i controlli della stessa altezza, interruttori allineati sulla stessa colonna, niente riquadri',
      'Più spazio fra i pulsanti dei menu: due bersagli attaccati si sbagliano',
      'Interruttori ON/OFF di larghezza fissa: cambiare stato non fa più ballare la riga',
    ], en: [
      'SETTINGS: every control the same height, switches on one column, no more boxes',
      'More room between menu buttons: two targets that touch get mis-tapped',
      'Fixed-width ON/OFF switches: changing state no longer makes the row jump',
    ],
  },
  {
    v: 'v0.72', it: [
      'IMPOSTAZIONI RIFATTE: schede per argomento, tutto in una schermata sola che si adatta a telefono e computer',
      'Audio e Lingua sono dentro le Impostazioni, non più due sottopagine da aprire',
      'Niente più comandi che finiscono fuori dallo schermo: il contenuto scorre davvero',
      'Statistiche in una schermata loro, così i salvataggi restano i protagonisti della loro',
    ], en: [
      'SETTINGS REBUILT: cards by topic, all on one screen that fits phone and desktop',
      'Audio and Language live inside Settings instead of two extra pages',
      'No more controls falling off the screen: the content actually scrolls',
      'Stats got their own screen, so your saves stay the point of theirs',
    ],
  },
  {
    v: 'v0.71', it: [
      'STATISTICHE della partita sotto i salvataggi: tempo di gioco, specie, teche, chimere, meraviglie, grotte, scavi',
      '"Partite" si chiama "Salvataggi": dice cosa c\'è dentro',
    ], en: [
      'GAME STATS under your saves: time played, species, cases, chimeras, wonders, caves, digs',
      '"Games" is now "Saves": it says what is actually in there',
    ],
  },
  {
    v: 'v0.70', it: [
      'SALVARE SU UNO SLOT PIENO ORA CHIEDE CONFERMA, e dice quale partita sta per sparire',
      'Il pulsante dell\'account dice subito se sei collegato, senza doverci entrare',
      'Se entri da un altro dispositivo, questo te lo dice appena torni sulla scheda',
      'Tutti i pulsanti del menu hanno la stessa larghezza',
    ], en: [
      'SAVING OVER A FULL SLOT NOW ASKS FOR CONFIRMATION, naming the game about to go',
      'The account button says right away whether you are signed in, without opening it',
      'If you sign in on another device, this one tells you as soon as you come back to the tab',
      'All menu buttons are the same width',
    ],
  },
  {
    v: 'v0.69', it: [
      'Anche i 3 salvataggi manuali viaggiano col tuo account: li ritrovi su ogni dispositivo',
      'Un dispositivo alla volta: entrando da un altro, il primo si scollega (la sua partita non viene mai toccata)',
      'Fra due partite diverse vince quella più avanti, e il gioco ti dice quale ha tenuto',
      'L\'accesso si vede subito sulla schermata iniziale, invece di essere sepolto nel menu',
      'Audio e Lingua sono passati nelle Impostazioni',
    ], en: [
      'Your 3 manual saves travel with your account too: find them on every device',
      'One device at a time: signing in elsewhere signs the first one out (its game is never touched)',
      'Between two different games the one further along wins, and the game tells you which it kept',
      'Sign-in is visible on the title screen instead of buried in the menu',
      'Audio and Language moved into Settings',
    ],
  },
  {
    v: 'v0.67', it: [
      'PARTITA IN CLOUD: entri con Google e ritrovi la stessa partita su telefono e computer',
      'Il salvataggio va sul server da solo mentre giochi, e appena chiudi la scheda',
      'Se due dispositivi hanno partite diverse, scegli tu quale tenere: non si sovrascrive mai da soli',
      'Prima di sovrascrivere si tiene una copia della partita che avevi qui',
      'Puoi cancellare account e partite dal server quando vuoi (la partita su questo dispositivo resta)',
    ], en: [
      'GAME IN THE CLOUD: sign in with Google and find the same game on phone and computer',
      'Your save goes to the server on its own while you play, and as soon as you close the tab',
      'If two devices hold different games, you choose which to keep: nothing is ever overwritten on its own',
      'Before overwriting, a copy of the game you had here is kept',
      'You can delete your account and server saves whenever you want (the game on this device stays)',
    ],
  },
  {
    v: 'v0.66', it: [
      'Il tempo scorre anche in grotta e dentro gli edifici: si esce all\'ora giusta (le finestre virano al blu quando cala la notte)',
    ], en: [
      'Time now passes in caves and indoors: you come out at the right hour (windows turn blue when night falls)',
    ],
  },
  {
    v: 'v0.65', it: [
      'Il pulsante Libro dentro lo zaino ora apre davvero il Libro',
      'Premere E davanti a un piedistallo del museo apre la scheda del reperto',
      'Lo zaino conta anche sottoterra: a zaino pieno il cristallo resta al suo posto',
      'Il ritiro al Museo non sfonda più lo zaino: quel che non entra resta lì e si ritira dopo',
      'Le missioni non danno più esperienza doppia (e non sprecano il totem della doppia XP)',
      'Il traguardo "le hai scoperte tutte" aspetta davvero tutte le specie, grotte comprese',
    ], en: [
      'The Book button inside the bag now actually opens the Book',
      'Pressing E at a museum pedestal opens the exhibit card',
      'The bag counts underground too: when full, the crystal stays where it is',
      'Museum pickup no longer overflows the bag: what does not fit stays there for later',
      'Missions no longer grant double XP (and no longer waste the double-XP totem)',
      'The "discovered them all" trophy now waits for every species, caves included',
    ],
  },
  {
    v: 'v0.64', it: [
      'Le specie RISVEGLIATE al Laboratorio ora passeggiano nel parco insieme alle chimere: prima il recinto le ignorava e sembravano perse',
      'Pulsante della mappa nella barra in alto anche su telefono',
      'La grotta ha un imbocco da cui si vede l\'esterno: si esce anche col solo mouse',
      'Zaino più capiente fin dall\'inizio (14 posti) e ingrandimenti meno cari',
      'Niente più energia negativa, e la barra in alto resta viva anche in grotta e negli interni',
      'Le città col Museo hanno un segno tutto loro sulla mappa',
      'Nomi delle chimere sempre distinguibili fra loro',
      'Pulsante Discord nel menu',
    ], en: [
      'Species AWAKENED at the Lab now roam the park alongside chimeras: the pen used to ignore them and they looked lost',
      'Map button in the top bar on phones too',
      'The cave mouth shows the outside world: you can leave with the mouse alone',
      'Roomier bag from the start (14 slots) and cheaper upgrades',
      'No more negative energy, and the top bar stays live in caves and indoors',
      'Towns with a Museum have their own mark on the map',
      'Chimera names always tell each other apart',
      'Discord button in the menu',
    ],
  },
  {
    v: 'v0.24', it: [
      'Funghi, conchiglie, fiori e canne MATURI si raccolgono: hanno ombra e stellina come gli altri oggetti',
      'Il primo disegno rifinito a mano è in gioco: il Gigante di Fieno',
      'Sprite Studio: disegni centrati, corna e pon-pon non più tagliati, apertura diretta con #id',
      'Il Libro delle Meraviglie mostra il disegno vero del gioco al posto del modello 3D',
      'Zaino a tutta altezza; su mobile spariscono i riferimenti ai tasti',
    ], en: [
      'RIPE mushrooms, shells, flowers and reeds can be picked: they have a shadow and a sparkle like other items',
      'The first hand-finished drawing is in the game: the Hay Giant',
      'Sprite Studio: centred drawings, horns and pompoms no longer cut off, direct opening with #id',
      'The Book of Wonders shows the real in-game art instead of the 3D model',
      'Full-height bag; on mobile the keyboard hints disappear',
    ],
  },
  {
    v: 'v0.21', it: [
      'SPRITE STUDIO (/sprites): tutti i disegni in un posto, editor pixel e codice pronto da incollare',
      'Meraviglie molto più rare e mai vicine fra loro; area di interazione ridotta a due passi',
      'Meraviglie ancorate al terreno come gli alberi: niente più contorni "adesivo"',
      'Suoni per chimere, risvegli, traguardi e lettere; avvisi HUD per energia bassa e zaino pieno',
      'Guida riapribile (zaino → ❔) e suggerimenti al primo incontro con ogni meccanica',
      'Città e interni coi materiali del bioma (tetti, lastricato, legno, neve sulle Lande)',
      'Barre di scorrimento a tema in ogni pannello',
    ], en: [
      'SPRITE STUDIO (/sprites): every drawing in one place, pixel editor and ready-to-paste code',
      'Wonders much rarer and never close together; interaction range cut to two steps',
      'Wonders grounded like the trees: no more "sticker" outlines',
      'Sounds for chimeras, awakenings, achievements and letters; HUD warnings for low energy and full bag',
      'Reopenable guide (bag → ❔) and first-time tips for every mechanic',
      'Towns and interiors built from biome materials (roofs, paving, wood, snow in the Wastes)',
      'Themed scrollbars in every panel',
    ],
  },
  {
    v: 'v0.20', it: [
      'Meraviglie ridisegnate: niente contorni, si integrano nel mondo come alberi e rocce',
      'Le ninfee crescono solo sull\'acqua; i blocchi massicci non si attraversano più',
      'MAPPA a pergamena con zoom (rotella, pinch, +/−) e punti cliccabili che dicono cosa sono',
      'Bilanciamento rifatto sui numeri veri: leggendari allo 0,6% ma con garanzia anti-sfortuna',
      'I doppioni non ti bloccano più: esce prima ciò che ti manca per la teca',
      'Le lettere del nonno sono nello zaino, in una scheda dedicata',
    ], en: [
      'Wonders redrawn: no outlines, they sit in the world like trees and rocks',
      'Lily pads only grow on water; massive blocks can no longer be walked through',
      'Parchment MAP with zoom (wheel, pinch, +/−) and clickable pins telling you what they are',
      'Rebalanced on real numbers: legendaries at 0.6% but with bad-luck protection',
      'Duplicates no longer wall you: what you are missing comes up first',
      "Grandpa's letters now live in the bag, in their own tab",
    ],
  },
  {
    v: 'v0.19', it: [
      'MERAVIGLIE: i 18 landmark sono ora enormi, si scoprono con un annuncio e hanno un dono',
      'Libro delle Meraviglie: quelle trovate si rivedono in 3D, le altre restano da cercare',
      'Archi d\'Ossa e Arco Rosso: attraversali per viaggiare da uno all\'altro',
      'MAPPA del mondo (tasto M) che si scopre camminando: città, meraviglie e X del tesoro',
      'Il Maestro Scavatore dice quanta XP manca e cosa ottieni al livello dopo',
    ], en: [
      'WONDERS: the 18 landmarks are now huge, announce themselves and grant a gift',
      'Book of Wonders: the ones you found can be viewed in 3D, the rest await discovery',
      'Bone Arch and Red Arch: walk through one to travel to another',
      'World MAP (key M) revealed by walking: towns, wonders and treasure Xs',
      'The Master Digger now tells you the XP left and what the next level grants',
    ],
  },
  {
    v: 'v0.18', it: [
      'LETTERE DEL NONNO: riempi una sala del Museo e il Curatore te ne consegna una (7 + il finale)',
      'Il Museo ha la SETTIMA ALA: le grotte hanno teche, pagine del Libro e risveglio',
      'Ogni sala del Museo ha la targa col nome del bioma e quante specie hai completato',
      'Economia ribilanciata: rarità corrette, fontana e grotte non sfondano più il gioco',
      'Salvataggio più sicuro: backup, avviso se il browser non può salvare, niente perdite silenziose',
      'Su mobile gli elenchi si scorrono col dito (zaino, negozio, libro, trofei)',
    ], en: [
      "GRANDPA'S LETTERS: fill a Museum room and the Curator hands you one (7 + the finale)",
      'The Museum has a SEVENTH WING: caves now have cases, Book pages and awakening',
      'Every Museum room has a plaque with its biome name and your progress',
      'Rebalanced economy: correct rarities, the fountain and caves no longer break the game',
      'Safer saving: backup, a warning when the browser cannot save, no more silent losses',
      'On mobile the lists scroll with your finger (bag, shop, book, trophies)',
    ],
  },
  {
    v: 'v0.16', it: [
      'Grotte: spiazzo libero davanti e un masso che le sigilla — serve il PICCONE per entrare',
      'I cristalli di grotta si staccano solo col piccone',
      'Zaino: sezioni Attrezzi e Mezzi, con in grigio quelli che ti mancano',
      'Il Maestro Scavatore gira dentro il Museo (niente più cappello volante)',
      'Avviso chiaro quando i cheat congelano il salvataggio',
      'Nel nome del personaggio si possono finalmente scrivere W, A, S, D, E, Z, Q…',
      'Il compagno NUOTA quando lo porti in barca (niente più camminate sull\'acqua)',
      'Barca sempre pronta: entri in acqua e ci sali da solo (col motoscafo parte il motoscafo)',
      'Bici e pattini ripartono da soli quando torni a terra',
    ], en: [
      'Caves: a clear yard in front and a boulder sealing them — you need the PICKAXE to get in',
      'Cave crystals can only be broken with the pickaxe',
      'Bag: Tools and Vehicles sections, with the missing ones greyed out',
      'The Master Digger now walks around inside the Museum (no more floating hat)',
      'Clear warning when cheats freeze your save',
      'You can finally type W, A, S, D, E, Z, Q… in the character name',
      'Your companion SWIMS when you take the boat out',
      'The boat is always ready: step into the water and you board it (motorboat wins if you own it)',
      'Bike and skates resume by themselves once you are back on land',
    ],
  },
  {
    v: 'v0.15', it: [
      'Risolto DAVVERO le scritte sovrapposte su mobile (era il line-height del canvas)',
      'Test E2E automatici sull\'HUD (niente più regressioni a sorpresa)',
      'Pulsanti Libro e Zaino sempre accessibili (anche a tocco); coin/energia sempre in vista',
      'Menu: "Nuova partita" + riga icone (Trofei, Novità, Comandi, Credits)',
      'Il Maestro Scavatore ora sta nell\'atrio del Museo (niente più cappello volante)',
      'Zaino: tolte le cinghie svolazzanti e le tasche laterali',
    ], en: [
      'REALLY fixed overlapping text on mobile (it was the canvas line-height)',
      'Automated E2E tests on the HUD (no more surprise regressions)',
      'Book and Bag buttons always accessible (touch too); coins/energy always visible',
      'Menu: "New game" + icon row (Trophies, News, Commands, Credits)',
      'The Master Digger now walks around inside the Museum (no more floating hat)',
      'Bag: removed the floating straps and side pockets',
    ],
  },
  {
    v: 'v0.14', it: [
      'Editor: nome del personaggio + tasto "Personaggio casuale"',
      'Intro rifatta: scena zoomata, prato con fiori, "tocca per continuare"',
      'Il dono del nonno è un fossile leggendario GREZZO da identificare al museo',
      'Museo: video tutorial al primo ingresso (bande cinema + dialoghi)',
      'Meteo e stagioni con transizioni graduali; coppe uniche nella Sala dei Trofei',
    ], en: [
      'Editor: character name + "Random character" button',
      'Reworked intro: zoomed scene, flowery meadow, "tap to continue"',
      'Grandpa\'s gift is a RAW legendary fossil to identify at the museum',
      'Museum: first-visit tutorial cutscene (cinema bars + dialogue)',
      'Gradual weather & season transitions; unique cups in the Hall of Fame',
    ],
  },
  {
    v: 'v0.13', it: [
      'Intro con la storia: sei il nipote del più grande archeologo!',
      'Mobile: libro a pagina singola, HUD collassabile, frasi non più sovrapposte',
      'NPC con 10 battute a testa + ringraziamenti quando compri',
    ], en: [
      'Story intro: you\'re the grandchild of the greatest archaeologist!',
      'Mobile: single-page book, collapsible HUD, no more overlapping lines',
      'NPCs with 10 lines each + thanks when you buy',
    ],
  },
  {
    v: 'v0.12', it: [
      'Fix: relitti/siti non "scattano" più camminando; piedi dentro la barca',
      'Città più distanti tra loro (più esplorazione)',
      'Baloon degli NPC: ti spiegano cosa fare',
      'Sala dei Trofei nel menu; changelog',
    ], en: [
      'Fix: wrecks/sites no longer "jitter" while walking; feet inside the boat',
      'Towns farther apart (more exploration)',
      'NPC speech balloons: they explain what to do',
      'Hall of Fame in the menu; changelog',
    ],
  },
  {
    v: 'v0.11', it: [
      'Missioni giornaliere + cartello in città (tasto Q)',
      'Compagni: una chimera/risvegliato ti segue e aiuta (fiuto/bussola/fortuna)',
      'Livelli archeologo (XP → più energia, scavo rapido, più rari)',
      'Achievement, landmark per bioma, meteo dinamico',
      'Creature animate (saltellano/strisciano/volano)',
      'Identificazione al museo ISTANTANEA',
    ], en: [
      'Daily missions + town notice board (press Q)',
      'Companions: a chimera/awakened follows and helps (sniff/compass/luck)',
      'Archaeologist levels (XP → more energy, faster digs, more rares)',
      'Achievements, biome landmarks, dynamic weather',
      'Animated creatures (they hop/slither/fly)',
      'INSTANT museum identification',
    ],
  },
  {
    v: 'v0.10', it: [
      'Musica che cambia col bioma (senza stacchi)',
      'Oggetti veri da raccogliere a terra; grotte più leggibili',
      'Zaino a schede; mezzi (pattini/bici/barca/motoscafo) attivabili',
      'Comandi console per provare tutto (goto, weather, season...)',
    ], en: [
      'Music that morphs with the biome (no cuts)',
      'Real collectible objects on the ground; clearer caves',
      'Tabbed bag; vehicles (skates/bike/boat/motorboat) toggleable',
      'Console commands to test everything (goto, weather, season...)',
    ],
  },
];
