/* BANCA DEGLI SPRITE — disegni rifiniti a mano che SOSTITUISCONO quelli generati a codice.
   Si compilano dalla pagina /sprites: disegni, esporti, incolli qui. Finché una voce non c'è,
   il gioco usa il disegno procedurale di sempre: la banca è additiva, non rompe nulla.

   Formato: id → { w, h, ax, ay, pal, rows }
     w,h   dimensioni in pixel
     ax,ay ANCORA: dove cade il punto (0,0) del disegno rispetto allo sprite (di solito
           ax = w/2 = centro, ay = h = base che poggia a terra)
     pal   mappa carattere → colore ('.' = trasparente, sempre)
     rows  righe di caratteri, una per riga di pixel

   Gli id seguono le categorie della pagina: 'wonder:menhir', 'deco:tree', 'icon:coin', … */
export const SPRITES = {
  /* GIGANTE DI FIENO — rifinito a mano nello Sprite Studio (Marco) */
  'wonder:haygiant': {
    w: 96, h: 80, ax: 48, ay: 71,   // ancora: la riga 71 è quella che poggia a terra
    pal: {"A": "#dcbe4c", "B": "#f0d070", "C": "#c9a227", "D": "#a8842a", "E": "#a97a4c", "F": "#8a5f38", "G": "#e2604f", "H": "#8a1f18", "I": "#c94f4a", "J": "#8a6a1a", "K": "#e8c860", "L": "#d4b13c", "M": "#5fa04e", "N": "#1e1914", "O": "#a78723", "P": "#18180f"},
    rows: [
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '........................................................A.......................................',
      '................................................................................................',
      '......................................................B.........................................',
      '.........................................CCCCCCCCCCCCC..........................................',
      '........................................CCCCCCCCCCCCCC..........................................',
      '........................................CCCCCCCCCCCCCC..........................................',
      '........................................CCCCCCCCCCCCCC..........................................',
      '.....................................AAAAAAAAAAAAAAAAAAAAA......................................',
      '....................................DDDDDDDDDDDDDDDDDDDDDD......................................',
      '....................................DDDDDDDDDDDDDDDDDDDDDD........E..E..E.......................',
      '.....................................DDDDDDDDDDDDDDDDDDDD.........E..E..E.......................',
      '........................................BBBBBBBBBBBBBB............E..E..E.......................',
      '.......................................BBBBBBBBBBBBBBBB...........E..E..E.......................',
      '.......................................BBBBBBBBBBBBBBBB...........FFFFFFF.......................',
      '.......................................AAAAAAAAAAAAAAAA...........FFFFFFF.......................',
      '.......................................DDDDDDDDDDDDDDDD..............FF.........................',
      '.......................................AAAAAGAAAAAAGAAA..............FF.........................',
      '.......................................AAAAHIAAAAAHIAAA..............FF.........................',
      '.......................................AAAAAAAAAAAAAAAA..............FF.........................',
      '.......................................DDDDDDDDDDDDDDDD..............FF.........................',
      '.......................................AAAAJAAAAAAAJAAA..............FF.........................',
      '........................................AAAAJJJJJJJAAA...............FF.........................',
      '.........................................AAAJJJJJJJAA................FF.........................',
      '..................................JJJJJJJJJJJJJJJJJJJJJJJJJJ.........FF.........................',
      '..................................JJJJJJJJJJJJJJJJJJJJJJJJJJ.........FF.........................',
      '....................................KKKKKKKKKKKKKKKKKKKKKK...........FF.........................',
      '........................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFF.........................',
      '.......................KKKKKKKKKKKKBKKKKKKBKKKBKKKBKKKKKKBKKKKKKKKKKKKK.........................',
      '.......................CCCCCCCCCCCCLLLLLLLLLLLLLLLLLLLLLLLLCCCCCCCCCCCC.........................',
      '........................CCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCCCF.........................',
      '...................................LLLLLLLLLLLLLLLLLLLLLLLL..........FF.........................',
      '...................................LLLLLLLLLLLLLLLLLLLLLLLL..........FF.........................',
      '...................................LLLLLLLLLLLLLLLLLLLLLLLL..........FF.........................',
      '...................................DDDDDDDDDDDDDDDDDDDDDDDD..........FF.........................',
      '...................................LLLLLLLLLLLLLLLLLLLLLLLL..........FF.........................',
      '...................................LLLLLLLLLLLLLLLLLLLLLLLL..........FF.........................',
      '....................................LLLLLLLLLLLLLLLLLLLLLL...........FF.........................',
      '....................................DDDDDDDDDDDDDDDDDDDDDD...........FF.........................',
      '.....................................LLLLLLLLLLLLLLLLLLLL............FF.........................',
      '...............................JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ......FF.........................',
      '...............................JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ......FF.........................',
      '................................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.......FF.........................',
      '................................KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.......FF.........................',
      '................................BKKKKKKBKKKBKKKBKKKKKKBKKKBKKK.......FF.........................',
      '................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC.......FF.........................',
      '................................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..................................',
      '................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '................................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..................................',
      '................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '.................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '.................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '.................................DDDDDDDDDDDDDDDDDDDDDDDDDDDDD..................................',
      '.................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '.................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '.................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCC..................................',
      '.............................MM..DDDDDDCCMMDMMDDDDDDDDCCMMDMM...................................',
      '.............................MMN..CMMOOCCMMOMMOOCCMMOOCCMMOMM.NCCMM.............................',
      '.............................MMNN.CMMPPCCPPPMMPPCCMMPPCCPPPMMPNCCMM.............................',
      '.............................NNNNNNNNNPPPPPPPPPPPPPPPPPPPNNNNNNNN...............................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
    ],
  },
  /* CEPPO CAVO — rifinito a mano nello Sprite Studio (Marco) */
  'wonder:hollowstump': {
    w: 96, h: 80, ax: 48, ay: 77,
    pal: {"A":"#c08b56","B":"#9a6b40","C":"#6e4a2a","D":"#140c06","E":"#a97a4c","F":"#3a2a18","G":"#5a7a4a","H":"#f2e07a","I":"#4e6a3f","J":"#d0453a","K":"#f6efdd","L":"#8a5f38","M":"#e8dcc0","N":"#4a3018","O":"#412c17","P":"#ac3c32","Q":"#1e1914","R":"#c0b59d","S":"#18180f"},
    rows: [
      '................................................................................................',
      '................................................................................................',
      '..................AAAAAAAAAAAAAAAAAAAAAA.............AAAAAAAAAAAAAAAAAAAAAAAAA..................',
      '...............AAAAAAAAAAAAAAAAAAAAAAAAAAAAA....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA................',
      '..............AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...............',
      '..............AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..............',
      '.............AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..............',
      '.............AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA..............',
      '.............AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCC.............',
      '.............AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCC.............',
      '.............AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCC.............',
      '.............AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBCCCCCCCCCCCCC.............',
      '.............AAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCC.............',
      '.............AAAAAAAAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '.............AAAAAEECCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCEECCCC............',
      '............AAAAAAEECCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCEECCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCC.............',
      '............AAAAAACCCCDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDCCCCCCCCC.............',
      '............AAAAAACCCCDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDCCCCCCCCC.............',
      '............AAAAAACCCCDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCC.............',
      '............AAAAAACCCCDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCC.............',
      '............AAAAAACCCCDDDDDDFFFFGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCC.............',
      '............AAAAAACCCCDDDDDDFFFFGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCC.............',
      '............AAAAAACCCCDDDDDDDDDDGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCC.............',
      '............AAAAAACCCCDDDDDDDDDDGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCC.............',
      '.............AAAAACCCCDDDDDDDDDDGGGGHHGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCC.............',
      '.............AAAAACCCCDDDDDDDDDDGGGGHHGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC..............',
      '.............AAAAACCCCDDDDDDDDDDGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC..............',
      '.............AAAAACCCCDDDDDDDDDDGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCC..............',
      '.............AAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCC.............',
      '.............AAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCC.............',
      '.............AAAAACCCCDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDCCCCCCCCCC............',
      '.............AAAAACCCCDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDCCCCCCCCCC............',
      '.............AAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDHHDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '.............AAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDHHDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '.............AAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDIIIIIIIIIIDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDIIIIIIIIIIDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDIIIIIIIIIIDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDIIIIIIIIIIDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDIIIIHHIIIIDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDIIIIHHIIIIDDDDDDDDCCCCCCCCCC............',
      '..............AAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '.............AAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCCCCC............',
      '.............AAAAACCCCDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDDDDDCCCCCCCCCC............',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCJJKKJJJJ........',
      '............AAAAAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCJJKKJJJJ........',
      '........JJKKJJJJAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCJJJJJJJJ........',
      '........JJKKJJJJAACCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCJJJJKKJJ........',
      '....LLLLJJJJJJJJLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJJJJKKJJLLLL....',
      '....LLLLJJJJJJJJLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLJJJJJJJJLLLL....',
      '....LLLLJJJJKKJJLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMLLLLLL....',
      '....LLLLJJJJJJJJLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMLLLLLL....',
      '....CCCCCCMMMMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCMMMMCCCCCC....',
      '....CCCCCCMMMMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCMMMMCCCCCC....',
      '....CCCCCCMMMMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC....',
      '....CCCCCCMMMMCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC....',
      '....CCCCCCCCCCCCCCJJKKJJJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC....',
      '....CCCCCCCCCCCCCCJJKKJJJJCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC....',
      '....GGGGNNNNNNNNNNJJJJJJIIIIGGGGNNGGGGNNNNNNNNNNNNNNNNIIIIGGGGNNGGGGNNNNNNNNNNNNNNNNIIIIGGGG....',
      '....GGGGNNNNNNNNNNJJJJJJIIIIGGGGNNGGGGNNNNNNNNNNNNNNNNIIIIGGGGNNGGGGNNNNNNNNNNNNNNNNIIIIGGGG....',
      '....GGGGOOOOIIIIGGGGPPPPIIIIGGGGOOGGGGOOOOIIIIGGGGOOOOII.IGGGGOOGGGGOOOOIIIIGGGGOOOOIIIIGG......',
      '......GGOOOOIIIIGGGGPPPPIIIIGGGGOOGGGGOOOOIIIIGGGGOOOOII..GGGGOOGGGGOOOOIIIIGGGGOOOOIII.G.......',
      '......GGQQQQIIIIGGGGRRRRIIIISSSSSSGGGGSSSSIII..GGGSSSSIII.SSSSSSGGGGSSSSII...GGGQQQQIII...QQ....',
      '.......GQQQQIIIIGGGGRRRRIIIISSSSSSGGGGSSSSIIII.GGGSSSSIIIISSSSSSGGGGSSSSII.......QQQIII..QQQ....',
      '......QQQQQQQQQQQQQQRRRRQQQQQQSSSSSSSSSSSSSSSS..SSSSSSSSSSSSSSSSSSSSQQQQQQQQQQQQ.QQQQQQQQQQQ....',
      '....QQQQQQQQQQQQQQQQRRRRQQQQQQSSSSSSSSSSSSSSSSS..SSSSSSSSSSSSSSSSSSSQQQQQQQQQQQQQQQQQQQQQQQQ....',
      '................................................................................................',
      '................................................................................................',
    ],
  },
  /* CERCHIO DI MENHIR — rifinito a mano nello Sprite Studio (Marco) */
  'wonder:menhir': {
    w: 97, h: 80, ax: 48, ay: 72,
    pal: {"A":"#a8a696","B":"#c6c2ae","C":"#8b8a86","D":"#5f6376","E":"#6e7183","F":"#d6d2bc","G":"#5f7a4a","H":"#7d9a5c","I":"#6f6a5c","J":"#f2e3a8","K":"#4e8d3f","L":"#5fa04e","M":"#75746f","N":"#5e606c","O":"#a4a08f","P":"#525462","Q":"#52673f"},
    rows: [
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '...............................................AAAAAA............................................',
      '..............................................AAAAAAAA...........................................',
      '..............................................BBBCCCDDC..........................................',
      '..............................................BBBCCCDDC..........................................',
      '..............................................BBBCCCDDC..........................................',
      '..............................................BBBCCCDDC..........................................',
      '..............................................BBBCCCDDC..........................................',
      '...........................AAAAA..............BBBCCCDDC.........AAA..............................',
      '..........................AAAAAAA.............BBBCCCDDC.......AAAAAAA............................',
      '..........................BBBCDDC.............BBBCCCDDC.......BBBCDDC............................',
      '..........................BBBCDDC.............BBBCCCDDC.......BBBCDDC............................',
      '..........................BBBCDDC...........BBBCECCCDDC.......BBBCDDC............................',
      '..........................BBBCDDC...........BBBCCCCCDDC.......BBBCDDC............................',
      '..........................BBBCDDC...........BBBCCCCCDDC.......BBBCDDC............................',
      '..........................BBBCDDC...........BBBCCCCCDDC.......BBBCDDC............................',
      '..........................BBBCDDC...........BBBCCCCCDDC.......BBBCDDC............................',
      '.........................BBBCCCDDC..........BBBCCCCCDDC.......BBBCCCDDC..........................',
      '..........FAAAA..........BBBCECDDC..........BBBCCCCCDDC.......BBBCCEDDC.........AAAAA............',
      '.........AAAAAAA.........BBBCCCDDC..........BBBCCCCCDDC.......BBBCCCDDC........AAAAAAA...........',
      '.........BBBCDDC.........BBBCCCDDC..........BBBCCCCCDDC.......BBBCCCDDC........BBBCDDC...........',
      '.........BBBCDDC.........BBBCCCDDC..........BBBECCCCDDC.......BBBCCCDDC........BBBCDDC...........',
      '.........BBBCDDC.........BBBCCCDDC..........BBBCCCCCDDC.......BBBCCCDDC........BBBCDDC...........',
      '.........BBBCDDC.........BBBCCCDDC..........BBBCCCCCDDC.......BBBCCCDDC........BBBCDDC...........',
      '.........BBBCDDC........BBBCCCCCDD..........BBBCCCCCDDC......BBBCCCCCDD........BBBCDDC...........',
      '.........BBBCDDC........BBBCCCCCDD..........BBBCCCCCDDC......BBBCCCCCDD........BBBCDDC...........',
      '.........BBBCCEDDC......BBBCECCCDD..........BBBCCCCCDDC......BBBCCECCDD.......BBBCECDDC..........',
      '.........BBBCCCDDC......BBBCCCCCDD..........BBBCCCCCDDC......BBBCCCCCDD.......BBBCCCDDC..........',
      '.........BBBCCCDDC......BBBCCCCCDD..........BBBCCCCCDDC......BBBCCCCCDD.......BBBCCCDDC..........',
      '.........BBBCCCDDC......BBBCCCCCDD..........AAAAAADADAC......BBBCCCCCDD.......BBBCCCDDC..........',
      '.........BBBCCCDDC......AAAAACCCDD.........AAAAAADDADA.......BBBCCCCAFAAAA....ABBCCCDDC..........',
      '.........BBBCCCDDC....AAAAAAACCCDD.........BBBBBCDDCDC.......BBBCCCCAAAAAAA...ABBCCCDDC..........',
      '.........BBBCCCDDC....BBBCDDCCCCDD.........BBBBBCDDCDC.......BBBCCCCBBBCDDC...BBBCCCDDC..........',
      '.........BBBCECDDC....BBBCDDCCCCDD.........BBBBBCDDCDC........BBBCCCBBBCDDC...BBBECCDDC..........',
      '.........BBBCCCDDC....BBBCDDCECCDD.........BBBBBCDDCDC........BBBCCEBBBCDDC...BBBCCCDDC..........',
      '.........BBBCCCDDC....BBBCDDCCCCDD.........BBBBBCDDCDC........BBBCCCBBBCDDC...BBBCCCDDC..........',
      '.........BBBCCCDDC....BBBCDDCCCCDD.........BBBBBCDDCDC........BBBCCCBBBCDDC...BBBCCCDDC..........',
      '.........BBBCCCDDC....BBBCDDGCCCDD.........BBBBBCDDCDC........BGGGGCBBBCDDC...BBBCCCDDC..........',
      '.........BBBCCCDDC...BBBCCCDDHCCDD.........BBBBBCDDCDC........BGGGGHBBBCCCDDC.BBBCCCDDC..........',
      '..........BBBCECDDC.BBBECCDDGCCCDD.......IIIBBBCECDDCIII......BGGGGCBBBCCEDDC.BBBCECDDC..........',
      '..........BBBCCCDDC.BBBCCCDDGCCCDDJ......IIIBBBCCCDDCIIIK.....BGGGGCBBBCCCDDC.BBBCCCDDC..........',
      '..........BBBCCCDDC.BBBCCCDDIIIIIIIL.....LL.BBBCJCDDCK.LL...IIIIIIIIBBBCCCDDC.BBBCCCDDC..........',
      '..........BBBCCCDDC.BBBCCCDDIIIIIIIL........BBBCCCDDC......KIIJIIIIIBBBCCCDDC.BBBCCCDDC..........',
      '..........BBBCCCDDC.BBBCCCDD....LLKK........BBBCCCDDC......KLLLL....BBBCCCDDC.BBBCCCDDC..........',
      '..........BBBCCCDDC.BBBCCCDDC...............BBBCCCDDC...............BBBCCCDDC.BBBCCCDDC..........',
      '........IIIIIIIIIIIIBBBCCCDDC..............BBBCCCCCDD...............BBBCCCDDCIIIIIIIIIIII........',
      '......LKKIIIIIIIIIIIBBECCCDDC..............BBBCCCCCDD...............BBBCECDDCIIIIIIIILLLIL.......',
      '......LK....KKL.....BBBCCCDDC..............BBBCECCCDD...............BBBCCCDDC.K..LKK.K..LL.......',
      '....................BBBCCCDDC..............BBHHCCCCDD...............BBBCCCDDC....................',
      '....................BBBCCCDDC..............BBBHCCCCDD...............BBBCCCDDC....................',
      '....................BBBCCCDDC..............BBBHCCCCDD...............BBBCCCDDC....................',
      '....................BBBCCCDDC..............BBBHCCCCDD...............BBBCCCDDC....................',
      '....................KKBCCCDDC..............BBLHKKCKKD................BBBCCCDDC...................',
      '...................BKKMNLLKK...............OOLLKKMKKP................BBKKNMDDC...................',
      '...................BKKMMLLKK...............OOLLMMMKKP................BBBKMMDDC...................',
      '...................BQQQQMPPM...............OOOMMMMMPP................OBOMMMPDC...................',
      '...................BGGGGHDDC...............BBBCCECCDD................BBBCCCDDC...................',
      '...................BGGGGCDDC...............BBBCCCCCDD................BBBCCCDDC...................',
      '...................BGGGGCDDC...............BBBCCCCCDD................BBBCCCDDC...................',
      '................LIIIIIIIIIIIII.............BGGGGCCCDD..............IIIIIIIIIIILL.................',
      '................LLILIIIIILLKKL.............BGGGGHCCDD.............LIIIIIILLLIIILLL...............',
      '...................LLKK..L.................BGGGGCCCDD.............LLL...KK.K.....................',
      '...........................................BGGGGCCCDD............................................',
      '.........................................IIIIIIIIIIIIII..........................................',
      '.........................................LLIIIIIIIIIILILLL.......................................',
      '..........................................L...KKL...LL...........................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
      '.................................................................................................',
    ],
  },
  /* ALBERO-MONDO — rifinito a mano nello Sprite Studio (Marco).
     È la meraviglia più alta del gioco (182 px, ~11 tile): l'eccezione voluta al limite
     di altezza in PIXELART.md. */
  'wonder:gianttree': {
    w: 96, h: 182, ax: 48, ay: 173,
    pal: {"A":"#94e27b","B":"#7ec069","C":"#7fd36a","D":"#6cb35a","E":"#649954","F":"#70bc5c","G":"#568f48","H":"#5fa04e","I":"#d8f5a0","J":"#a8e87a","K":"#5ca64a","L":"#4c803e","M":"#4e8d3f","N":"#4a933c","O":"#3e7032","P":"#3f7d33","Q":"#376e2c","R":"#326428","S":"#2f5e26","T":"#254b1e","U":"#805a36","V":"#6e4a2a","W":"#563820","X":"#7d5735","Y":"#5c3d22","Z":"#2f2318","a":"#1d150e","b":"#1e1914","c":"#382716","d":"#5e4025","e":"#18180f"},
    rows: [
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '...................................................A............................................',
      '..........................................AAAAAAAAAAA...........................................',
      '........................................AAAAAAAAAAAAAA..........................................',
      '......................................BBBBBBBBBBBBBBBBB.........................................',
      '......................................BBBBBBBBBBBBBBBBBB........................................',
      '.....................................BBBBBBBBBBBBBBBBBBB........................................',
      '.....................................BBBBBBBBBBBBBBBBBBB........................................',
      '.....................................BBBBBBBBBBBBBBBBBBB........................................',
      '.....................................BBBBBBBBBBBBBBBBBBB........................................',
      '.................................CCCCBBBBBBBBBBBBBBBBBBBCCCC....................................',
      '.................................CCCCBBBBBBBBBBBBBBBBBBBCCCCC...................................',
      '................................CCCCCBBBBBBBBBBBBBBBBBBBCCCCCC..................................',
      '................................DDDDDBBBBEBBEBBEBBEBBEBBEDDDDD..................................',
      '................................DDDDDBBBBBBBBBBBBBBBBBBBDDDDDDD.................................',
      '................................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................................',
      '..............................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................................',
      '..............................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................................',
      '..............................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................................',
      '..............................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................................',
      '............................FFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFF..............................',
      '...........................FFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDFFFF.............................',
      '...........................FFFDDDDGDDDDGDDDDGDDDDGDDDDGDDDDGDDDFFFFF............................',
      '...........................HHHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDHHHHH............................',
      '...........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH............................',
      '..........................HHHHHHIHHHHHHHHHHHHHHHHHHHJHHHHHHHHHHHHHHHH...I.......................',
      '..........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................',
      '.........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................',
      '.........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................',
      '........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................',
      '........................HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH...........................',
      '.....................KKKHHHHJHHHHHHHHHHHHHHHHHHHIHHHHHHHHHHHHHHHHHHHJKK.........................',
      '.....................KKKHHHHLHHHHHHLHHHHHHLHHHHHHLHHHHHHLHHHHHHLHHHHHKKK........................',
      '....................KKKKHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHKKK........................',
      '....................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.......................',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.......................',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.......................',
      '...................MMMMMIMMMMMMMMMMMMMMMMMMMJMMMMMMMMMMMMMMMMMMMIMMMMMMMMM..........J...........',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......................',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......................',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......................',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......................',
      '...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......................',
      '.................NNMJMMOMMMMMMMMOMMMMMMMIOMMMMMMMMOMMMMMMMMOJMMMMMMMOMMMMMN.....I...............',
      '.................NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN....................',
      '................NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...................',
      '................PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP...................',
      '................PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '...............PIPPPPPPPPPPPPPPPPPPPJPPPPPPPPPPPPPPPPPPPIPPPPPPPPPPPPPPPPPPPJP..................',
      '...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '...............PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..................',
      '..............QPPPPRPPPPPPPPPRPPPPPPPPPRPPPPPPPPPRPPPPPPPPPRPPPPPPPPPRPPPPPPPPQ.................',
      '.............QQPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQ.................',
      '.............QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ................',
      '............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................',
      '............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................',
      '............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............',
      '.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................',
      '.............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................',
      '...............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS................',
      '................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................',
      '.................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................',
      '.................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...................',
      '.................SSSSSSSSSSTSSSSSSSSSSTSSSSSSSSSSTSSSSSSSSSSTSSSSSSSSSSTSSSSS...................',
      '...................SSSSSSSSSSS.UUU.UUSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....................',
      '...............................UUUUUUUUUUUUUVVVVVVWWWV....VVVVWW................................',
      '.................................UUUUUUUUUUUVVVVVVWWWV...VVVVVWW................................',
      '...................................UUUUUUXYYYYVVVVWWWV..VVVVWWW.................................',
      '.....................................UUUUYYYYYVVVVWWWV.VVVWWW...................................',
      '......................................UUUYYYYYVVVVWWWVVVVWWW....................................',
      '.......................................UUUUUVVVVVVWWWVVWWWW.....................................',
      '.......................................UUUUUVVVVVVWWWVWWWW......................................',
      '.......................................UUUUUVVVVVVWWWVWWW.......................................',
      '.......................................UUUUUVVVVVVWWWVWW........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVXYYYVWWWV.V........................................',
      '............................YY.........UUUUUVYYYYVWWWVVVVVVVVVVVVV..............................',
      '..........................YYYVV........UUUUUVYYYYVWWWVVVVVVVVVVVVVVV............................',
      '..........................YYYVVV.......UUUUUVVVVVVWWWVYYYYYYYYYYYYYY............................',
      '.............................VVVV......UUUUUVVVVVVWWWVYYYYYYYYYYYYY.............................',
      '.........................VVVVVVVVVVVVVVUUUUUVVVVVVWWWV..........................................',
      '........................VVVVVVVVVVVVVVVUUUUUVVVVVVWWWV..........................................',
      '........................YYYYYYYYYYYYYYYUUUUUVVVVVVWWWV..........................................',
      '.........................YYYYYYYYYYYYYYUXYYUVVVVVVWWWV..........................................',
      '.......................................UYYYUVVVVVVWWWV..........................................',
      '.......................................UYYYUVVVVVVWWWV...............VVVV.......................',
      '.......................................UUUUUVVVVVVWWWV..............VVVVV.......................',
      '.......................................UUUUUVVVVVVWWWV.............VVVYYY.......................',
      '.......................................UUUUUVVVVVVWWWV...........VVVVYY.........................',
      '.......................................UUUUUVVVVVVWWWV..........VVVVVY..........................',
      '.......................................UUUUUVVVVVVWWWVVVVVVVVVVVVVVVVVVV........................',
      '.......................................UUUUUXYYYYVWWWVVVVVVVVVVVVVVVVVVVV.......................',
      '.......................................UUUUUYYYYYVWWWVYYYYYYYYYYYYYYYYYYY.......................',
      '.......................................UUUUUYYYYYVWWWVYYYYYYYYYYYYYYYY..........................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUZZZZZZZZZWWV..........................................',
      '.......................................UUUZaaaaaaaZWWV..........................................',
      '.....................VVVVVVVVVVVVVVVVVVUUUZaaaaaaaZYWV..........................................',
      '....................VVVVVVVVVVVVVVVVVVVUUUZaaaaaaaZYWV..........................................',
      '....................YYYYYYYYYYYYYYYYYYYUUUZaaaaaaaZYWV..........................................',
      '.....................YYYYYYYYYYYYYYYYYYUUUZZZZZZZZZWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUXYYVVVVWWWV..........................................',
      '.......................................UUUUYYYVVVVWWWV..........................................',
      '.......................................UUUUYYYVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVXYYYYWV..........................................',
      '.......................................UUUUUVVVYYYYYWV..........................................',
      '.......................................UUUUUVVVYYYYYWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUXYYYVVVVWWWV..........................................',
      '.......................................UUUYYYYVVVVWWWV..........................................',
      '.......................................UUUYYYYVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVXYYVWWWV..........................................',
      '.......................................UUUUUVVYYYVWWWV..........................................',
      '.......................................UUUUUVVYYYVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUXYYYYVVVVWWWV..........................................',
      '.......................................UUYYYYYVVVVWWWV..........................................',
      '.......................................UUYYYYYVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVXYYYVWWWV..........................................',
      '.......................................UUUUUVYYYYVWWWV..........................................',
      '.......................................UUUUUVYYYYVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UUUUUVVVVVVWWWV..........................................',
      '.......................................UXYYUVVVVVVWWWV..........................................',
      '...............................VVVVVVVVUYYYUVVVVVVWWWV..VVVVVVVV................................',
      '.............................VVVVVVVVVVVVVVUVVVVVVWVVVVVVVVVVVVVVVV.............................',
      '............................YYYYYYYYYVVVVVVUVVVVVVWVVVVVYYYYYYYYYYY.............................',
      '................HH........MMHHYHHYYYYYYYYMMHHVHHVVWYYYYYMMHHYHHYYYY....MMHH.HH..................',
      '................HHbbMMHHbbMMHHcHHccMMHHccMMHHdHHddMMHHccMMHHcHHccMMHHbbMMHHbHH..................',
      '................HHbbMMHHbbMMbbbHHeeMMHHeeMMeeeHHeeMMHHeeMMeeeHHbbMMHHbbMMbbbHH..................',
      '................bbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbbbbbb....................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
      '................................................................................................',
    ],
  },
  /* SCHELETRO DI DRAGO (figlio di Neladan) — rifinito a mano nello Sprite Studio (Marco) */
  'wonder:ribcage': {
    w: 117, h: 80, ax: 58, ay: 56,
    pal: {"A":"#5f5642","B":"#f8f2e2","C":"#e6ddc7","D":"#9c917a","E":"#c3b79a","F":"#c9b98f","G":"#d8c9a0","H":"#1e1914","I":"#524a38","J":"#beb6a3","K":"#ccc7b8","L":"#18180f","M":"#b3a684"},
    rows: [
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '..........................AB...AAAA..................................................................................',
      '.........................A.BCAABBBBAAAA..............................................................................',
      '........................A.BCDABBCCCBBBB............ABAABA............................................................',
      '.......................ABBCDBACCDDDDCCC...........A.BCCBAA...........................................................',
      '......................A.BCDBAC.DAAAADDD...........ABAADCBBA..........................................................',
      '.....................A.BCDAACDAA....AAA..........ABBCADDCBBA..............................................A..........',
      '.....................BBCDCADDAA..................ABCCAAADCCBAA............................................AB.........',
      '...............ABBBBBBCDCAD.A....................B.CCCAAADCBBA..........................................AABAA........',
      '...............ACCCCCCCAADAA....................ABCCCD.AAADDCBAA........................................ABA..........',
      '.........BBBBBBBBCCCAACCCAAA...................ABCCCCDAAAAADCCBAA.....................................AABAA..........',
      '........ACCCCCCCCCCCAACCCCDAA..................ABCCCDAA.AAAADDCBBA....................................ABA............',
      '.........CCCCCCCCCCCCCCCCCCDDA................ABC.CCDA..A.AAAADCBAA.................................AABAA............',
      '...............ADDDDDDDDDDCCDDAA..............ABCCCDA....ADAAAADCBBA................................ABA..............',
      '..........EEEEEEEEE...ABBCCAAADAA............ABCC.CDA.....AACAADDC.BA.............................AABAA..............',
      '...........C.C.C.C.C...ABBCCCCCDDA..........AABCCCDA......ADAAAAADCCBA............................ABA................',
      '........................AABACACCDDAA........ABCCCCDA.........A.ACADC.BA.........................AABAA................',
      '.........................AABBCCCCCDA.......A.BCCCDA...........ADAAADCCBAA.......................ABA..................',
      '...........................ABBCCCC.DAA.....ABCCC.A.............ADA.AD.CBA....................AAABAA..................',
      '............................AABCCCCCD.A...AB.CCCDA.AAAAAAAAAAAA.ADADADDCBBA.................A.CBA....................',
      '.............................AAB.CC.CDAA..ABCCCDDABBBBBBBBBBBBBBAADADADBCB.A...............ABBACA....................',
      '...............................ABBCAAADDAAB.CACDAB.CCCCAAACCCCCCBAADA.AADCBBA.............A.BCD.A....................',
      '................................A.BCCCCD.A.CCCDBACCCCCCCCCCCCCCCC.ADAAAACDCB.A...........ABBCDAA.....................',
      '.................................ABACACCDDABBCDACAAAADCBAADCBAAACBCB.AA.AADCCBA........AABCCD.A......................',
      '..................................AABC.CCBDAABCADCBAADCBBADCBBCCCCBAAAAADACDCABA......AABCACAA.......................',
      '...................................A.BCCCCDCCCBADCBBAADCBAADCBAADCBACCB.AAAADCCBAAA.AABBCCDAA........................',
      '....................................AAB.CCCADCBAADCBAADCBBADCBBADCBACCCBBAAAAAAAAAAA.BCCDDAA.........................',
      '......................................ABCCCADCBAADCBB.ADCBAADCBADCBBADCCCBBBBBBBBBABBCACDA...........................',
      '......................................AA..AADCCC.ADCBAADCBAADCBAADCCBACCCCACCCACCCCCDD.AA............................',
      '..........................................ADCDCBBADCBAADCBBADCBBADCCBBACCCCCCCCCCCADAAA..............................',
      '..........................................ADCCCBAADCBB.ADCBAADCBDCCCCBAADDACCCACCDDDA................................',
      '.........................................ADC.CCBAAADCBAADCBAADCBADCCCABAABDDDDDDDAAAA................................',
      '......................FF........GGFF.FF..ADCCCBGGFFDFFAADCBAAAGGFFDFFCCDAAAAAGGFFAFF.................................',
      '......................FFHHGGFFHHGGFFHFFHIGGFFJKGGFFIFFIIGGFFLIGGFFIFFJJGGFFHHGGFFHFFHHGGFF...........................',
      '......................FFHHGGFFHHGGHHHFFHIGGFFKIGGLLIFFLLGGFFLIGGLLIFFJJGGFFHHGGHHHFFHHGGFF...........................',
      '....................GGMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMGGGGGG.....................',
      '.....................GGGFFFF.FF..FFFFFFFFFFF...FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFGG.......................',
      '......................GGFFFF......FFFFFFFF...........FFFFFFFFFF.......FFFFFFFFFFFFFFFFFFFF...........................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
      '.....................................................................................................................',
    ],
  },
  /* MOTOSCAFO di FRONTE (scafo + parabrezza, l'eroe resta quello vivo del gioco) — Marco */
  'vehicle:motorboat:down': {
    w: 20, h: 30, ax: 10, ay: 19,
    pal: { "A": "#eef2f4", "B": "#3d8ba0", "C": "#8fd0e6", "D": "#2b6274", "E": "#bfe9f4" },
    rows: [
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....AAAAAAAAAAAA....',
      '....AAAAAAAAAAAA....',
      '....AAAAAAAAAAAA....',
      '....BBBBBBBBBBBB....',
      '....BBBCCCCCCBBB....',
      '.....DDEEEEEEDD.....',
      '.......AAAAAA.......',
      '.........AA.........',
      '......E......E......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
  },
  /* MOTOSCAFO di SPALLE (si allontana): scafo + MOTORE fuoribordo a poppa — Marco */
  'vehicle:motorboat:up': {
    w: 20, h: 30, ax: 10, ay: 19,
    pal: { "A": "#eef2f4", "B": "#3d8ba0", "C": "#2b6274", "D": "#33291f", "E": "#bfe9f4", "F": "#20323f" },
    rows: [
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....AAAAAAAAAAAA....',
      '....AAAAAAAAAAAA....',
      '....AAAAAAAAAAAA....',
      '....BBBBBBBBBBBB....',
      '....BBBBBBBBBBBB....',
      '.....CCDDDDDDCC.....',
      '.......DDDDDD.......',
      '.......DDDDDD.......',
      '......E..FF..E......',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
  },
  /* MOTOSCAFO di PROFILO: scafo affusolato, parabrezza, motore fuoribordo a poppa — Marco */
  'vehicle:motorboat:side': {
    w: 29, h: 30, ax: 14, ay: 20,
    pal: { "A": "#8fd0e6", "B": "#bfe9f4", "C": "#33291f", "D": "#9aa3a8", "E": "#eef2f4", "F": "#3d8ba0", "G": "#20323f", "H": "#2b6274" },
    rows: [
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '............AAAAA............',
      '............BBBBB............',
      '............BBBBB............',
      '....CC.....DDDDDDD...........',
      '....CCEEEEEEEEEEEEEEEEEE.....',
      '....CCEEEEEEEEEEEEEEEEEEE....',
      '...CCCEEEEEEEEEEEEEEEEEEEE...',
      '...CCCEFFFFFFFFFFFFFFFFFF....',
      '....CGFFFFFFFFFFFFFFFFFF.....',
      '.....HHHHHHHHHHHHHHHHHH......',
      '.............................',
      '........B..........B.........',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
      '.............................',
    ],
  },
  /* BICI di FRONTE: manubrio + ruota di taglio, DAVANTI all'eroe — Marco */
  'vehicle:bike:down': {
    w: 20, h: 30, ax: 10, ay: 21,
    pal: { "A": "#33291f", "B": "#7a6a58", "C": "#c94f4a", "D": "#2a2016", "E": "#9a9285", "F": "#c9c2b2" },
    rows: [
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.....A.........A....',
      '.....AAAAAAAAAAA....',
      '..........B.........',
      '..........C.........',
      '.........DCD........',
      '.........DCD........',
      '.......A.....A......',
      '........D.E.D.......',
      '....................',
      '.........DFD........',
      '.........D.D........',
      '..........D.........',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
    ],
  },
};

export function hasSprite(id) { return !!SPRITES[id]; }
export function spriteDef(id) { return SPRITES[id] || null; }
/* disegna uno sprite della banca col pennello del render (rect/px), ancorato come il disegno
   procedurale che sostituisce: (x,y) è lo stesso punto che riceverebbe la funzione originale */
export function drawSprite(g, id, x, y) {
  const d = SPRITES[id]; if (!d) return false;
  const ox = x - (d.ax || 0), oy = y - (d.ay || 0);
  for (let r = 0; r < d.rows.length; r++) {
    const row = d.rows[r];
    let c = 0;
    while (c < row.length) {
      const ch = row[c];
      if (ch === '.') { c++; continue; }
      let run = 1;                                   // righe orizzontali in un colpo solo
      while (c + run < row.length && row[c + run] === ch) run++;
      const col = d.pal[ch];
      if (col) g.rect(ox + c, oy + r, run, 1, col);
      c += run;
    }
  }
  return true;
}
export function spriteCount() { return Object.keys(SPRITES).length; }
